apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - name: k01
      type: git
      url: https://github.com/satoruh/k01
  application.instanceLabelKey: argocd.argoproj.io/instance
  url: https://argocd.k01.satoruh.org
  oidc.config: |
    name: Auth0
    issuer: https://dev-bikatfwumhltuxb2.us.auth0.com/
    clientID: $argocd-oidc:oidc.auth0.clientID
    clientSecret: $argocd-oidc:oidc.auth0.clientSecret
    requestedScopes:
    - openid
    - profile
    - email
    - 'http://your.domain/groups'
