apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/satoruh/k01/
    targetRevision: HEAD
    path: manifests/applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
