apiVersion: v1
kind: Service
metadata:
  name: load-balancer-service
  namespace: sandbox
  labels:
    app.kubernetes.io/name: example
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nginx.example.satoruh.org
spec:
  selector:
    app: nginx
  ports:
  - port: 8000
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
