apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: coredns
spec:
  selector:
    matchLabels:
      kubernetes.io/name: CoreDNS
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: metrics
