apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  config:
    server:
      root_url: 'https://grafana-k01.satoruh.org'
    security:
      admin_user: root
      admin_password: secret
  service:
    spec:
      type: LoadBalancer
