apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: kube-state-metrics
spec:
  podMetricsEndpoints:
    - port: http-metrics
      scheme: http
      path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: kube-state-metrics
  namespaceSelector:
    matchNames:
      - kube-system
