resources:
- namespace.yaml
- vmcluster.yaml
- vmagent.yaml
- node-exporter.yaml
- node-exporter-vmnodescrape.yaml
- grafana.yaml
- vmselect-grafanadatasource.yaml
- victoriametrics-cluster-grafanadashboard.yaml
- victoriametrics-vmagent-grafanadashboard.yaml
